// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSV.Data;

namespace QLSV.Migrations
{
    [DbContext(typeof(QLSVDBContext))]
    [Migration("20211212190824_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QLSV.Data.GiaoVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenGV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGV");

                    b.ToTable("GiaoVien");
                });

            modelBuilder.Entity("QLSV.Data.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("QLSV.Data.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenMH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMH");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("QLSV.Data.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("QLSV.Data.ThongTinSinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LopMaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SinhVienMaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LopMaLop");

                    b.HasIndex("SinhVienMaSV");

                    b.ToTable("ThongTinSinhVien");
                });

            modelBuilder.Entity("QLSV.Data.ThongTinSinhVien", b =>
                {
                    b.HasOne("QLSV.Data.Lop", "Lop")
                        .WithMany("ThongTinSinhVien")
                        .HasForeignKey("LopMaLop");

                    b.HasOne("QLSV.Data.SinhVien", "SinhVien")
                        .WithMany("ThongTinSinhVien")
                        .HasForeignKey("SinhVienMaSV");

                    b.Navigation("Lop");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QLSV.Data.Lop", b =>
                {
                    b.Navigation("ThongTinSinhVien");
                });

            modelBuilder.Entity("QLSV.Data.SinhVien", b =>
                {
                    b.Navigation("ThongTinSinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
